// Auto-generated mqjs_stdlib.h header
// This file is generated by gen_mqjs_headers.py

#ifndef MQJS_STDLIB_H
#define MQJS_STDLIB_H


// Minimal standard library for Wily JavaScript interpreter
const char *mqjs_stdlib = " \
    // Global Wily Utility functions \
    wily.log = function(...args) { wily.println(...args); }; \
";

#endif // MQJS_STDLIB_H
